name: Update nightly release

on:
  push:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Update Nightly
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/libs/*.*
